#-------------------------------
# Site Settings
title: yeste.studio
logo: # You can add own logo. For example '/images/logo.png'.
author: Javier Sánchez Yeste
description: Artistic website for Javier Sánchez Yeste

#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Works'
      url: 'works'
    - title: 'Shows'
      url: 'shows'
    - title: 'Software'
      url: 'software'
    - title: 'Bio'
      url: 'bio'
    - title: 'Contact'
      url: 'contact'
#    - title: 'Blog'
#      url: 'blog'


#-------------------------------
# Hero Settings
hero:
  hero__title:
  hero__description: 'In this website you can find the work of Javier Sánchez Yeste:'


#-------------------------------
# Portfolio Settings
#portfolio:
#  portfolio__title: Portfolio
#  portfolio__gallery:
#    - image: /images/question2.jpg
#      title: MusaDSL
#      description: MusaDSL <a href="/musa-dsl">MusaDSL</a>


#-------------------------------
# Subscribe Settings
#mailchimp:
#  mailchimp__title: Get updates and digital art inspiration # Add your Title
#  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
#  mailchimp__button__text: Subscribe # Add your button text.
#  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
#- {icon: "logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
#- {icon: "logo-facebook", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
#- {icon: "logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
#- {icon: "logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
#- {icon: "logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com"}
#- {icon: "logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}
- {icon: "logo-github", color: "#24292e", label: Github, link: "https://github.com/javier-sy"}
- {icon: "logo-soundcloud", color: "#1393cd", label: Soundcloud, link: "https://soundcloud.com/yeste-studio"}
# - {icon: "logo-youtube", color: "#c4302b", label: Youtube, link: "https://youtube.com/yeste-studio"}

# Example of adding a new link to the footer section - {icon: "logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/


#-------------------------------
# Contact Settings
contact:
  email: javier@yeste.studio # Add your email for contact form
  description: Write me a note! Will answer as soon as possible.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

#disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-RSN5GV4Y4T # Add your identifier. For example UA-99631805-1.